### PR TITLE
Fix percentage value bug

### PR DESCRIPTION
**Pull request by equweiyu**
test `<div style="width: 50%;background-color: red;">test</div>`

### CODE REVIEW

**Comment by daohoangson** [comment]
Do you have a screenshot of the test HTML before and after the fix?

**Comment by equweiyu** [comment]
test code 
`HtmlWidget("""<div style="width: 50%;background-color: red;">test</div>""")`

before
Simulator Screen Shot - iPhone 13 - 2022-02-08 at 14 31 52

after
Simulator Screen Shot - iPhone 13 - 2022-02-08 at 14 31 44

**Comment by daohoangson** [comment]
Thank you for the screenshots.

**Comment by daohoangson** [comment]
Thank you @equweiyu for the PR. flutter_widget_from_html_core `v0.8.5+1` has been released with your fix.

**Pull request merged**
