### PR TITLE
Add support for `HtmlWidget.renderMode`

### PR DESCRIPTION
**Pull request by daohoangson**
WidgetFactory breaking changes:

- `buildColumnPlaceholder` removed `trimMarginVertical` named param
- `buildColumnWidget` removed `tsh` param
- `onTapAnchor` replaced `anchorContext` param with `scrollTo`

### CODE REVIEW

**Comment by daohoangson** [comment]
Check out this screen recording (demo_app, Android, release mode): https://youtu.be/5U10W0VJHOA

- Ignoring the parsing phases: shown in video with the circle indicator
- `Column` takes 1s (skipped ~60 frames) to render / layout.
- `ListView` takes 30ms (skipped 2 frames) to do that
- `SliverList` takes 17ms (skipped a frame) 
- After the first frames, scrolling is stable at 60fps in all modes (thanks to the `RepaintBoundary`)
-

**Comment by DFelten** [comment]
Looks really good :) The demo app with the huge html feels great. Thanks for this feature!

**Comment by DFelten** [comment]
This feature works really great! The HTML as a column also works very well, but especially when using for example iFrames within the HTML the performance as a list is much better.

I tried the Branch with our current app and am really happy with the performance :) I hope that the feature can be merged into the master soon.

**Comment by daohoangson** [comment]
@DFelten that's great to hear. There are a few things that are not working yet so the PR needs some more work. E.g. anchor doesn't work, big `DIV` performance is not great yet, etc.

**Comment by DFelten** [comment]
The performance of large divs are of course more difficult to solve. Simply splitting them is not possible, because otherwise information might be lost. In my opinion, the current variant of the splitting is fine for a first version. It is described that the variant works for articles with a flat div hierarchy. This can be used well as a basis for further improvements. Either way, performance is better than rendering everything in columns :)

Of course it would be great if the anchor links work again. This should be included in any case.

**Comment by DFelten** [comment]
I've tried several things to get the anchor links to work. Currently the big problem is to load the whole list once to get all positions. 

- I've tried to animate to to the bottom via a scroll controller and the `maxScrollExtent` of the list, store each position in a map and later animate to this position together with ensure visibility. Here of course the problem is the first animation to the bottom. I'm not sure if it's possible to hide this animation from the user. Another problem is that the size of the images is not known. Therefore, the calculated position may be wrong.
- An other possibility is to build the whole list once as columns and then as Sliver. There is currently no way to change this within the widget. This is currently only possible from the outside. To make that possible, some rebuilding would probably have to be done.
- You could also increase the cacheExtent, but that's only possible via the CustomScrollView, which is not part of the HTML widget.

I hope there is a better option here that I don't know about yet :) 

In the moment we have handle the anchor links from the outside, since we currently split the HTML ourselves. This is necessary for larger HTML especially if iFrames are available. The performance is otherwise unfortunately bad on older devices. This is of course due to the platform views of the WebViews.

**Comment by daohoangson** [comment]
I'm thinking about keying each list item and keep track of their visibility. Then an anchor scroll is needed, it should be possible to know which direction to scroll (up or down). After each scrolling, just check anchor position (if it's in range) and repeat.

**Comment by DFelten** [comment]
Yes, that could work. Good idea.

[This package](https://pub.dev/packages/indexed_list_view) also has an interesting approach. As far as I can see, it also scrolls in the respective direction until the item becomes visible. We have modified the whole thing for one of our own lists. But maybe this helps.

**Comment by DFelten** [comment]
We would like to replace flutter_html with your package soon. The SliverList is essential for this. 

Currently we have to split the document ourselves and use the HTML widget multiple times. This would allow us to control the anchor links from the outside as before (As in the example shown). 

Of course, it would be best if the render mode and the anchor links becomes part of the package. Have you already achieved results here? Can we assist you with the task somehow?

**Comment by daohoangson** [comment]
The aforementioned approach seems to work. I have a few implements to toy with that idea already.

**Comment by DFelten** [comment]
That's great to hear :) I'm looking forward to it.

**Comment by daohoangson** [comment]
The anchor implementation is up @DFelten 🚀

**Comment by DFelten** [comment]
Thanks, it's working :) The only problem with very long articles is currently that scrolling is very slow or takes a long time.

**Comment by daohoangson** [comment]
@DFelten yeah, the huge html is quite slow. There's probably some optimizations to make but it will still take some time in the end.

**Comment by DFelten** [comment]
@daohoangson I think the duration of 50 milliseconds looks better than 100. At least it feels better in my tests.

One idea here would be to make the value overwritable from the outside. This way, everyone can adjust the value according to their own taste.

**Comment by daohoangson** [comment]
In my testings, lowering the duration prevented it from working... That's why I kept it at 100ms. I'll do some more tests. Exposing the duration is possible but not ideal though, I want to avoid having a constructor with too many params.

**Comment by DFelten** [comment]
For me it also works at 30, but if I set the value too low, I also get an error. For example, a value of 10 will stop too early. The list of new indexes is built too late or the lists are still identical.

But maybe it depends on how strong the device is and how slow it is when building the widgets. 

Couldn't the value rather be overwritten via the core Widget Factory? Then we don't need a larger constructor here either.

**Comment by DFelten** [comment]
I have just tested a little more. You are right, with a value of 50 it does not work with all articles. But even with 100 there are problems if the article is too long or there are too many images.

**Comment by daohoangson** [comment]
The latest commit changed the way scrolling is done so it's much faster and more reliable. Please try it if you have a chance @DFelten. I think this PR is almost ready now, it maybe merged into `next` pretty soon.

**Comment by DFelten** [comment]
The speed is so much better :) Thanks for the latest update, so this can definitely be merged.

**Comment by daohoangson** [comment]
`v0.7.0-dev.2021061301` has been released with this feature. Please try upgrading and let me know if it works for you @DFelten

**Pull request merged**
