### PR TITLE
Fix "text-align: right" doesn't work

### PR DESCRIPTION
**Pull request by ConanXie**

### CODE REVIEW

**Comment by daohoangson** [comment]
Right-aligned text is put into a `_TextAlignBlock` which will expand its width by itself. 

https://github.com/daohoangson/flutter_widget_from_html/blob/83ae6c683f8f429d6e506d07e6058a0ca705cbb4/packages/core/lib/src/internal/ops/style_text_align.dart#L33-L39

What is your HTML that is not working?

**Comment by ConanXie** [comment]
It works fine on initial rendering, but fails after next rendering (like hot reload), here are some screenshots.
Screenshot_20201020-152314972
Screenshot_20201020-152705282
Screenshot 2020-10-20 152802
Screenshot 2020-10-20 152938

**Comment by daohoangson** [comment]
This is a weird bug. I'll try to reproduce from your screenshot. Are you on the latest version of the package?

**Comment by ConanXie** [comment]
yes, the version is 0.5.1+3, and Flutter is 1.22.2

**Comment by daohoangson** [comment]
Closing in favor of #359. This is a bug with text-align, forcing stretch is not enough to fix it.

**Pull request closed without merging**
