### PR TITLE
Declare and apply text style field

### PR DESCRIPTION
**Pull request by foxanna**
With this PR I suggest exposing `style` field from `HtmlWidget` so that users could customize text style with Dart core rather than Html. This way`HtmlWidget` would have more traditional widgets api.
Currently, the same result can be achieved with `DefaultTextStyle(style: style, child: HtmlWidget(text))`, which is less convenient and requires advanced knowledge in Flutter.

### CODE REVIEW

**Comment by daohoangson** [comment]
I think this is a great idea!

**Comment by foxanna** [comment]
If you find suggested changes satisfying, probably it is worth merging them. Otherwise, we can discuss improvements I should make before you merge.

**Comment by daohoangson** [comment]
I intend to make a few changes on top of yours:

1. Only uses `DefaultTextStyle` if a specific style is given (not null)
1. Add tests to validate the logic above 

If you can do that in your PR, that would be great.

**Comment by foxanna** [comment]
Of course!
You were right about style not being `null` as it appears to be the required parameter of `DefaultTextStyle`. 
I'll be glad to work on tests as well.

**Comment by daohoangson** [comment]
Looks great, I'll merge as soon as the tests are in 👍

**Comment by daohoangson** [comment]
Hi @foxanna,

I have reimplemented this in cf42a707ef705ac99b2c6502d19b5cfd70228999 without the need for a `DefaultTextStyle` container. This can be done because of a `Builder` rewrite for 0.2.0.

**Comment by daohoangson** [comment]
v0.2.0 has been released with the `textStyle` param so I'm closing this PR now. 

Thank you @foxanna for your contribution.

**Comment by foxanna** [comment]
Thanks for the improvement, @daohoangson!

**Pull request closed without merging**
