### PR TITLE
Re-implement table layout

### PR DESCRIPTION
**Pull request by daohoangson**
Related to #346

### CODE REVIEW

**Comment by misterfourtytwo** [comment]
how's it going? do you need any help?

**Comment by daohoangson** [comment]
Most of the tasks have been completed, only one is left now: (see #346 )

> - [ ] Add support for COLGROUP, COL tag

I hope to have some free time and finish it this weekend.

**Comment by DFelten** [comment]
Great Merge Request :) On my test app there was an intrinsics crash on the html content of [this article](https://www.elderscrollsportal.de/news/allgemein/screenshotwettbewerb-2020-die-gewinner/3956), but with this branch it's working.

**Comment by misterfourtytwo** [comment]
when the new version with fixed tables will be released?

**Comment by daohoangson** [comment]
The checks are all green so hopefully in a few days. There are still some small details that need taken care of.

**Comment by Skyost** [comment]
Hey, do you have any news on this one ?

**Comment by DFelten** [comment]
What's the state of the table MR at the moment? We want to evaluate shortly whether we want to use this package or continue to use flutter_html for our apps. The tables are of course essential for this.

**Comment by Skyost** [comment]
Does this pull request also gives us a way to configure table borders color ?

**Comment by daohoangson** [comment]
> Does this pull request also gives us a way to configure table borders color ?

Yes, this PR includes a new border parser which allows each table cell to has its own color.



> What's the state of the table MR at the moment? We want to evaluate shortly whether we want to use this package or continue to use flutter_html for our apps. The tables are of course essential for this.

It does the job but there are a few goals are not done yet so I'm hesitant to merge because the remaining goals may require further refactors. That said, I'll cut a new RC right away so people can give it a try.

**Comment by daohoangson** [comment]
[v0.5.2-rc.2021011801](https://pub.dev/packages/flutter_widget_from_html/versions/0.5.2-rc.2021011801) has been released!

**Pull request merged**
