### PR TITLE
[HOLD] Update chewie once again to 0.11.0

### PR DESCRIPTION
**Pull request by urakozz**
Chewie got back to live and received nice updates!
Let's create a tag with this update 😊

### CODE REVIEW

**Comment by daohoangson** [comment]
Does it work well for you? It's rendering in wrong aspect ratio in my testings...

**Comment by urakozz** [comment]
@daohoangson oh, right, I managed to discover it too. Well, I could try to fix this issue, could you create a release in the meantime for the previous update we did? It looks like code is in the master, but there is no tag for it yet 👀

**Comment by daohoangson** [comment]
Yes, it's in `master` but I caught the bug so I haven't tagged it for release just yet.

**Comment by daohoangson** [comment]
Apparently 0.12.0 is out... The maintainers are adding features at high speed, making it unstable. I'm going to replace it with a basic version to support both video and audio (see #347), hopefully soon.

In the mean time, can you bump your PR to include 0.12.0 @urakozz? I'll merge and release a new version so user of `flutter_widget_from_html` can choose any of the compatible versions of `chewie` as needed.

**Comment by daohoangson** [comment]
I'm closing this in favor of #373 to add support for chewie@0.12

**Pull request closed without merging**
