### PR TITLE
chewie version upgraged - Flutter 3.10 compatible

### PR DESCRIPTION
**Pull request by Manty-K**

### CODE REVIEW

**Comment by shukmuni** [comment]
someone need to merge this PR on urgent bases

**Comment by daohoangson** [comment]
The current version constraint `^1.0.0` should allow app to use `chewie@1.5.0` without issue. Did you encounter any error in your app?

**Comment by Manty-K** [comment]
After inserting `flutter_widget_from_html 0.10.0` in `pubspec.yaml` file and performing  `flutter pub get`.
`chewie 1.0.0` is getting downloaded which is not compatible with Flutter 3.10

`flutter pub deps` logs
```
fwfh_chewie 0.7.1+1
│   │   ├── chewie 1.0.0
│   │   │   ├── wakelock 0.4.0
│   │   │   │   ├── wakelock_macos 0.1.0+3
│   │   │   │   │   ├── flutter...
│   │   │   │   │   ├── flutter_web_plugins...
│   │   │   │   │   └── wakelock_platform_interface...
│   │   │   │   ├── wakelock_platform_interface 0.2.1+3
│   │   │   │   │   ├── flutter...
│   │   │   │   │   └── meta...
│   │   │   │   ├── wakelock_web 0.2.0+3
│   │   │   │   │   ├── flutter...
│   │   │   │   │   ├── flutter_web_plugins...
│   │   │   │   │   ├── js...
│   │   │   │   │   └── wakelock_platform_interface...
│   │   │   │   ├── flutter...
│   │   │   │   └── meta...
│   │   │   ├── cupertino_icons...
│   │   │   ├── flutter...
│   │   │   └── video_player...
```

**Comment by daohoangson** [comment]
Normally pub will pick the latest version but your app probably has some other dependency that doesn't compatible with `chewie@1.5` so pub has to pick 1.0. A full output of `pub get` would be helpful here.

If you don't need VIDEO tag support, using `flutter_widget_from_html_core` is another option. It will be faster too.

**Pull request closed without merging**
