### PR TITLE
Relax video_player dependency to allow 0.11

### PR DESCRIPTION
**Pull request by dgilperez**
Hi! 

I just bumped at a dependency error while upgrading video_player, now `0.11.0` so I thought I let you know. The minor breaking change does not seem to affect this package. 

Please let me know if this is an acceptable PR or do you require any more changes. 

EDIT: 

Now `chewie` is the problem, they forbid video_player 0.11.

`flutter pub get` outputs

```
Because chewie 0.9.10 depends on video_player >=0.7.0 <0.11.0 and no versions of chewie match >0.9.10 <0.10.0, chewie ^0.9.10 requires video_player >=0.7.0 <0.11.0.

And because every version of flutter_widget_from_html from git depends on chewie ^0.9.10, every version of flutter_widget_from_html from git requires video_player >=0.7.0 <0.11.0.
```

Any workaround?

### CODE REVIEW

**Comment by daohoangson** [comment]
I think this looks good from the POV of this package. The playback speed change doesn't break anything here.

Regarding `chewie`, I guess you'll have to open a PR over there.

I can merge this right now but there is a slight chance that `chewie` may do a major bump after your PR (if you decide to do it) so I'll wait a few days before merging this. 

Btw, the `video_player` document suggests expanding the upper constraint to v1.0.0 even. Let's do it in your PR here!

**Comment by dgilperez** [comment]
Thanks for the quick reply! I just checked that there is already a PR for this on chewie repo: https://github.com/brianegan/chewie/pull/367 - let's see how fast it can go, the cheview repo looks to be receiving not a lot of maintenance ...

**Comment by daohoangson** [comment]
Sorry for not being clear in my earlier comment, we should expand constraint to allow v1 which means it should be <2...

> The plugin has reached a stable API, we guarantee that version 1.0.0 will be backward compatible with 0.10.y+z. Please use video_player: '>=0.10.y+x <2.0.0' as your dependency constraint to allow a smoother ecosystem migration. For more details see: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0

**Comment by daohoangson** [comment]
I have opened another PR with your commits to bump the upper constraint to `<2.0.0` as suggested by video_player's publisher and allow CI jobs to run. 

Closing this now in favor of #333.

**Comment by dgilperez** [comment]
Thanks a lot for the speed!

**Pull request closed without merging**
