### PR TITLE
Add image loading builder to core widget factory

### PR DESCRIPTION
**Pull request by DFelten**
This pull request adds an image loading builder to the `CoreWidgetFactory`. With the help of this it is possible to adjust the loading behavior of the images for example with a loading indicator or a loading shimmer. The default behavior does not change, because a sized box with the height and width of 0 is returned.

Such a loading widget is especially useful if the HTML widget is built into a list and not all images are loaded directly. Also in columns with a weak internet connection or many images a loading widget is advantageous.

A shimmer builder for example would look like this within the app:

```dart
@override
Widget imageLoadingBuilder(
  BuildContext context,
  Widget child,
  ImageChunkEvent? loadingProgress,
) {
  if (loadingProgress == null) return child;
  return Shimmer.fromColors(
    baseColor: const Color(0xFFBDC0D1),
    highlightColor: const Color(0xFFBDC0D1),
    child: Container(
      width: double.infinity,
      height: double.infinity,
      decoration: const BoxDecoration(
        color: Colors.white,
      ),
    ),
  );
}
```

Alternatively to the changes in the pull request, instead of the loading builder, we could just overwrite the loading widget. The code would then look like this:

```dart
loadingBuilder: (context, child, loadingProgress) {
  if (loadingProgress == null) return child;
  return buildImageLoadingWidget(context, loadingProgress);
},
```

```dart
/// Builds loading widget for an image.
Widget buildImageLoadingWidget(
  BuildContext context,
  ImageChunkEvent? loadingProgress,
) =>
    const SizedBox.shrink();
```

### CODE REVIEW

**Comment by daohoangson** [comment]
What do you think about externalizing the `errorBuilder` too? 

Another question: should we pass the `BuildMetadata` to the callbacks?

**Comment by DFelten** [comment]
> What do you think about externalizing the `errorBuilder` too?

True, being able to control that from the outside makes sense. I have created one. The provider is not needed there I think. It is currently only needed for the print, which I left in `buildImageWidget`. In my opinion you don't need the print here either. What do you think?

> Another question: should we pass the `BuildMetadata` to the callbacks?

A good idea, I've added the meta data. They can certainly be helpful.

**Comment by daohoangson** [comment]
> In my opinion you don't need the print here either

Agree.

> I've added the meta data.

I noticed that we had to pass the semantic label to the error builder, which is not a good design... Let me think more about this.

**Comment by DFelten** [comment]
Instead of the semantic label we could use the `ImageMetadata`. Unfortunately, this would then be a breaking change, since we would also have to pass the value on to `buildImageWidget` and from there to the error builder.

I would prefer to move this to a separate merge request. Then we can insert the loading builder here and include an error widget builder separately.

**Comment by daohoangson** [comment]
> Instead of the semantic label we could use the ImageMetadata. Unfortunately, this would then be a breaking change...

Exactly 😢 I was worried about that. But if is something useful then it's okie to break the public api. This package is still pre-1.0.0 anyway.

> I would prefer to move this to a separate merge request. Then we can insert the loading builder here and include an error widget builder separately.

If it is decided, let's do them both at once to keep the history clean. Sorry for this, please bear with me.

**Comment by DFelten** [comment]
> > Instead of the semantic label we could use the ImageMetadata. Unfortunately, this would then be a breaking change...
> 
> Exactly 😢 I was worried about that. But if is something useful then it's okie to break the public api. This package is still pre-1.0.0 anyway.

You're right and I think a breaking change here is better then a bad design. I replaced the semantic label with the `ImageMetadata`. I like it better that way :) I like it better that way. We have a more consistent interface this way. What do you think?

**Comment by daohoangson** [comment]
Oops, I meant to open a PR targeting yours but apparently you allowed maintainer to commit directly to your branch... Sorry for the sudden commit.

I tried to simplify `buildImageWidget` so there are only two params left: the build meta and a `ImageSource`. It is possible to obtain the `ImageMetadata` from the source via a getter which uses an `Expando` to keep track of the parent image. Looks good?

**Comment by DFelten** [comment]
> Oops, I meant to open a PR targeting yours but apparently you allowed maintainer to commit directly to your branch... Sorry for the sudden commit.

This is exactly why I allowed changes to the branch. I am currently still in the process of familiarizing myself with the package. Of course, you have the better overview here and can optimize my adjustments. Thanks for that!


> I tried to simplify `buildImageWidget` so there are only two params left: the build meta and a `ImageSource`. It is possible to obtain the `ImageMetadata` from the source via a getter which uses an `Expando` to keep track of the parent image. Looks good?

Thanks for these changes, this is indeed the better solution. So it's easy to use.

**Comment by daohoangson** [comment]
I have published new pre-releases (version `0.7.0-dev.2021051501`) for core, enhanced and svg packages assuming you sent this PR so you can customize these in your app. Let me know if it doesn't work. 

Thank you for the contribution 👍

**Comment by DFelten** [comment]
Thank you, I'm glad my changes were integrated!

**Pull request merged**
