### PR TITLE
Expand roman support to 3999

### LINKED ISSUE #639: Expand roman support via Numerus
## Use case

Roman number support is currently very limited.

https://github.com/daohoangson/flutter_widget_from_html/blob/949cf49e490d5450ea434d53a3be2ed4d9f0179a/packages/core/lib/src/core_widget_factory.dart#L490-L505

## Proposal

https://pub.dev/packages/numerus has support up to 65535 which is... quite useful.

### PR DESCRIPTION
**Pull request by ngthailam**
Closes #639 

# Changes
Add function to convert int to roman numerals ( from 1 to 3999 )

Also: 
- Add tests ( copied from numerus package )
- Add to demo screen

# Screenshot
Screenshot 2024-01-10 at 14 56 40

### CODE REVIEW

**Comment by ngthailam** [comment]
This is a nice package so I'd like to contribute, I took the liberty to address this issue https://github.com/daohoangson/flutter_widget_from_html/issues/639

I'm not yet familiar with the coding style/conventions of this package, so please drop a review if you see any issues. 

 Please have a look @daohoangson Thanks

**Comment by daohoangson** [comment]
This looks great, thank you for the contribution. I have kicked off the pipeline runs, it they are all green then I'll merge it.

**Comment by daohoangson** [comment]
Sorry, the demo screen is too long so I had to revert that file.

**Comment by ngthailam** [comment]
@daohoangson no problem

**Pull request merged**
