### PR TITLE
refactor: add EagerGestureRecognizer to webview

### PR DESCRIPTION
**Pull request by stanislav216**

### CODE REVIEW

**Comment by daohoangson** [comment]
What does this do?

**Comment by stanislav216** [comment]
In the webview_flutter package, there is a gesture detector parameter. I passed EagerGestureRecognizer in this parameter to enable content scrolling inside the WebView if the HtmlWidget is inside a ListView. Perhaps you need to add this parameter to the HtmlWidget to allow developers to choose the gesture detector for the WebView themselves.

https://github.com/daohoangson/flutter_widget_from_html/assets/134495346/9f36c0c5-9da6-4e0a-8296-1aa2bb84c39c


https://github.com/daohoangson/flutter_widget_from_html/assets/134495346/9beeb556-a018-4a3f-b352-125763daa032

**Comment by stanislav216** [comment]
Here is an example of HTML iframe content that will not be scrollable if the HtmlWidget is inside a ListView.

<iframe src="https://teamup.com/ksg6ruh9554fy3m7u7?showSearch=0&showProfileAndInfo=0&showSidepanel=0&disableSidepanel=0&showViewSelector=0&showMenu=0&showAgendaHeader=1&showAgendaDetails=0&showYearViewHeader=1" style="width: 100%; height: 400px; border: 1px solid #cccccc" loading="lazy" frameborder="0"></iframe>

**Comment by xalabax** [comment]
@stanislav216 
Thank, it work.

**Comment by daohoangson** [comment]
Closing in favor of #1268 where I added new getter so app developer can customize the gestures as needed.

**Pull request closed without merging**
