### PR TITLE
Add support for `line-height`

### PR DESCRIPTION
**Pull request by daohoangson**
Related to #181

### CODE REVIEW

**Comment by daohoangson** [comment]
Waiting for https://github.com/flutter/flutter/pull/58766

**Comment by kamleshwebtech** [comment]
How to use line-height style? Please suggest.

**Comment by daohoangson** [comment]
Just put it in your HTML, something like this:

```html
<span style="line-height: 2">foo bar</span>
```

**Comment by kamleshwebtech** [comment]
> Just put it in your HTML, something like this:
> 
> ```
> <span style="line-height: 2">foo bar</span>
> ```

I cannot change html contents because it is fetching from third party api. Any other suggestion? Please share. Thanks.

**Comment by daohoangson** [comment]
Do you want to change the line height for the entire HTML or just some element?  If you need it for everything, just put your HTML inside a big div, like this

```dart
final lineHeight2 = '<div style="line-height: 2">$html</div>';
```

**Comment by kamleshwebtech** [comment]
As per your suggestion mentioned on below link page

https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/enhanced

under heading "Inline stylings", you suggested that we can add line-height "line-height: normal number or values in em, %, pt and px"

but when i add line-height attribute under TextStyle function as param, it does not work. Please see my code:

```
Container(
      padding: EdgeInsets.symmetric(vertical: 20.0, horizontal: 15.0),
      child: HtmlWidget(
      pageDescription,
      webView: true,
      textStyle: TextStyle(
        fontSize: 16.0,
        **lineHeight: '30em'**
    ),
  ),
),
```

fontSize works but lineHeight does not work.

Kindly suggest how can i use line-height attribute / property? Thank you. Look forward to hear you.

**Comment by kamleshwebtech** [comment]
System shows an error like "The named parameter 'lineHeight' isn't defined." after adding lineHeight: '30em'. Please suggest.

**Comment by daohoangson** [comment]
The inline styling mentioned in the README must be used in the HTML, similar to my sample earlier:

```dart
final lineHeight2 = '<div style="line-height: 2">$html</div>';
```

You cannot put it as a parameter of `TextStyle`. If you don't want to use line styling as above, you can use param `height` of `TextStyle`. I do not recommend doing that because if you set `TextStyle.height`, it is impossible to reset it later (see this [flutter/flutter issue](https://github.com/flutter/flutter/issues/58765)).

**Comment by kamleshwebtech** [comment]
> The inline styling mentioned in the README must be used in the HTML, similar to my sample earlier:
> 
> ```dart
> final lineHeight2 = '<div style="line-height: 2">$html</div>';
> ```
> 
> You cannot put it as a parameter of `TextStyle`. If you don't want to use line styling as above, you can use param `height` of `TextStyle`. I do not recommend doing that because if you set `TextStyle.height`, it is impossible to reset it later (see this [flutter/flutter issue](https://github.com/flutter/flutter/issues/58765)).

Bravo!! You made my day and saved my life, thanks :)

**Pull request merged**
