### PR TITLE
Add support for `HtmlWidget.isSelectable`

### PR DESCRIPTION
**Pull request by daohoangson**
Related to #102

### CODE REVIEW

**Comment by bksubhuti** [comment]
I still cannot select anything in the demo app.  Hello World

**Comment by daohoangson** [comment]
There is a popup menu on the app bar. You need to tap it and enable selectable.

**Comment by bksubhuti** [comment]
okay

**Comment by JesseBlackman** [comment]
@daohoangson hi, after adding isSelectable: true, the click event on the whole HtmlWidget not work. maybe the event was cached by SelectableText?

**Pull request merged**
